Resources:
  S3PolarsVsPandasAccessPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: S3PolarsVsPandasAccessPolicy
      Description: Lambda policy to allow access to SSM
      Path: /
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:PutObject
              - s3:DeleteObject
            Resource:
            - 'arn:aws:s3:::your_bucket_name/*'
            - 'arn:aws:s3:::your_bucket_name*'